### PR TITLE
[WIP] Add github actions

### LINKED ISSUE #34: Add GitHub actions
Add GitHub actions that will automatically:
- [ ] Compile the project 
- [ ] Run the tests

### PR DESCRIPTION
**Pull request by ClientCrash**
Closes #34

### CODE REVIEW

**Comment by ClientCrash** [comment]
I get the following error when running vlang with :

 `./v ./Peregrine/peregrine.v -o peregrine` output : 
`builder error: 'builtin/' not included on module lookup path.
Did you forget to add vlib to the path? (Use @vlib for default vlib)`
What can i do @SaptakBhoumik

**Comment by ClientCrash** [comment]
I will look into it later. I cant run actions right now and idk why, Sorry for the many commits but they are necessary to test the action as i cant do this localy. @SaptakBhoumik

**Comment by ClientCrash** [comment]
@SaptakBhoumik please review.

**Comment by SaptakBhoumik** [comment]
@ClientCrash Run the test_runner.py to run the  .pe file

**Pull request merged**
